### PR TITLE
Adding Azure speech, translate and CV tools

### PR DESCRIPTION
**Pull request by ajhofmann**
One question about this; adding the files to the `data` folder is nice for the demos, but we should make sure we aren't packaging the notebooks directory in our pip package, since the files are going to start making the download needlessly large.

### CODE REVIEW

**Comment by jerryjliu** [comment]
> One question about this; adding the files to the `data` folder is nice for the demos, but we should make sure we aren't packaging the notebooks directory in our pip package, since the files are going to start making the download needlessly large.

regarding that point could we upload to dropbox and just `wget` it?

**Comment by ajhofmann** [comment]
> > One question about this; adding the files to the `data` folder is nice for the demos, but we should make sure we aren't packaging the notebooks directory in our pip package, since the files are going to start making the download needlessly large.
> 
> regarding that point could we upload to dropbox and just `wget` it?

For this file I think we can actually just download it from the source, will look into the other files in the `data` folder to see whats worth refactoring into dropbox.

**Comment by ajhofmann** [comment]
https://github.com/emptycrown/llama-hub/assets/10040285/beb34bcc-0b31-4042-a7a7-1725ecc86e5c

DV demo, working on a demo video for the speech tools

**Comment by jerryjliu** [comment]
awesome!

**Review by jerryjliu — APPROVED** [review]
looks good! 

out of curiosity did you end up using dropbox?

**Pull request merged**
