### PR TITLE
feat: add apify actor and dataset reader

### PR DESCRIPTION
**Pull request by drobnikj**
Adds integration with the [Apify](https://apify.com/) platform. Apify is a web scraping and data extraction platform. You can use it to get content from documentation, knowledge bases, help centers, or blogs.

Apify welcomes all developers, they can sign up for a free account [here](https://console.apify.com/sign-up).

**Usage:**
```
import os

os.environ["APIFY_API_TOKEN"] = "apify_token"
os.environ["OPENAI_API_KEY"] = "openai_token"

from llama_index import download_loader
from llama_index.readers.schema.base import Document
from langchain.llms import OpenAI
from langchain.chains.question_answering import load_qa_chain
from llama_index import GPTSimpleVectorIndex

def tranform_dataset_item(item):
    return Document(
        item.get("text"),
        extra_info={
            "url": item.get("url"),
        },
    )

ApifyActor = download_loader('ApifyActor')
reader = ApifyActor(os.environ.get('APIFY_API_TOKEN'))
documents = reader.load_data(
    actor_id="apify/website-content-crawler",
    run_input={"startUrls": [{"url": "https://gpt-index.readthedocs.io/en/latest"}], "maxCrawlPages": 1},
    dataset_mapping_function=tranform_dataset_item,
)
print(documents)

index = GPTSimpleVectorIndex.from_documents(documents)

response = index.query("What is LlamaIndex?")
print(response)

response = index.query("How we call LlamaIndex before?")
print(response)
```
**Log:**
```
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_nodes] Total embedding token usage: 14554 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 1550 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 6 tokens

LlamaIndex is a project that provides a central interface to connect your LLM's (Language Model) with external data. It provides tools to ingest and index data, query the index, and customize the index for use with LLMs. It also offers a comprehensive toolset to trade off cost and performance.

INFO:llama_index.token_counter.token_counter:> [query] Total LLM token usage: 1503 tokens
INFO:llama_index.token_counter.token_counter:> [query] Total embedding token usage: 8 tokens

Before LlamaIndex, the project was known as GPT Index.
```

### CODE REVIEW

**Comment by drobnikj** [comment]
@jancurn I put it in draft for now let's sync about the final readme content.

**Comment by jerryjliu** [comment]
thanks, this is great! let me know when ready to review

**Comment by drobnikj** [comment]
> thanks, this is great! let me know when ready to review

Cool, we just need to polish the texts. We will let you know.

**Comment by jancurn** [comment]
Thanks guys, I've updated the copy and naming a bit, so it's good to go IMHO. @drobnikj please can you set the PR as ready to review?

**Comment by drobnikj** [comment]
@jancurn and @fnesveda Thank you for editing!

**Comment by drobnikj** [comment]
It is ready. You can review it. @jerryjliu 🚀

**Comment by drobnikj** [comment]
I created a simple recording of one run from Jupiter, you can use it as you like.

https://user-images.githubusercontent.com/11837643/232569034-9403bb16-bb0e-4a94-b81f-993ad2d9ee25.mov

You can find Apify's twitter here -> https://twitter.com/apify

**Comment by jerryjliu** [comment]
this is great, thanks

**Review by jerryjliu — APPROVED** [review]

**Pull request merged**
