### PR TITLE
Refactor load_data for consistent sheet handling and cleaner code

### PR DESCRIPTION
**Pull request by guyy1232**
This PR addresses an issue in the `load_data` function when reading a specific sheet from an Excel file and performs code simplification. 

Issues Addressed:
1. Previously, reading a single sheet resulted in inconsistent behavior where the returned Document object contained a text char-by-char with \n between each.
2. Redundant parentheses were found around `self._row_joiner`.

Changes Made:
1. Modified how `sheet_name` is processed always to treat it as a list, ensuring consistent behavior across single or multiple sheet name inputs.
2. Removed the unnecessary parentheses from `self._row_joiner` for cleaner code.
3. Renamed the variable `keys` to `sheet_names` for better clarity.
4. Updated the function's docstring to be more descriptive and accurate.

By implementing these changes, the function is now more robust and can handle different input scenarios effectively. Additionally, the code has been streamlined for better readability.

### CODE REVIEW

**Comment by guyy1232** [comment]
Hi @jerryjliu,
Is there anything missing for you to review the PR?
Let me know if anything should be done.
Thanks!

**Comment by jerryjliu** [comment]
@guyy1232 sorry for the delay! reviewing now

**Review by jerryjliu — CHANGES_REQUESTED** [review]
approving this, though one comment. is it possible to keep `include_sheetname` as the variable? changing it might break backwards compatibility

**Review by jerryjliu — APPROVED** [review]

**Review by guyy1232 — COMMENTED** [review]
renamed include_sheet_name back to "include_sheetname" for back compatibility (removed the "_")

**Comment by EmanuelCampos** [comment]
nice one

**Pull request merged**
