### PR TITLE
json_entry_added_etc

### PR DESCRIPTION
**Pull request by sangwongenip**
1.Deleted 'hangeul' directory, whose contents are same with 'hwp'. Sorry for my mistake.
2.Added entry for extra info.

thanks!

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
@sangwongenip I just realized, neither hangeul nor hwp were added to library.json right? could we add that? thanks

**Comment by sangwongenip** [comment]
> @sangwongenip I just realized, neither hangeul nor hwp were added to library.json right? could we add that? thanks

Yep!

**Comment by sangwongenip** [comment]
> @sangwongenip I just realized, neither hangeul nor hwp were added to library.json right? could we add that? thanks

I'll do it in 30 minutes!

**Comment by jerryjliu** [comment]
thanks!

**Review by jerryjliu — APPROVED** [review]

**Pull request merged**
