### PR TITLE
Revert "GithubRepositoryReader tests and minor fixes"

### PR DESCRIPTION
**Pull request by ahmetkca**
I have never done revert PR. I had some last minute changes to the `github-reader-test-and-fix` branch which fixes the github repo reader filter logic

### CODE REVIEW

**Comment by jerryjliu** [comment]
no worries, i'm reverting in #100 :) 

do you want to put out another try at this PR after the revert lands?

**Comment by ahmetkca** [comment]
@jerryjliu should I commit to `revert-73-github-reader-test-and-fix` branch?

**Comment by ahmetkca** [comment]
you already reverted in #100. I am closing this

**Comment by jerryjliu** [comment]
> @jerryjliu should I commit to `revert-73-github-reader-test-and-fix` branch?

yeah maybe just create a new PR?

**Pull request closed without merging**
