### PR TITLE
Salesforce Tool

### PR DESCRIPTION
**Pull request by chrispangg**
This PR for merging the Salesforce Tool to main. Already tested (see screenshot). Working as expected.

### CODE REVIEW

**Comment by chrispangg** [comment]
Tool Tested: working

image

**Comment by jerryjliu** [comment]
nice!! will take a look soon

**Review by jerryjliu — COMMENTED** [review]
looks good, one comment

**Review by jerryjliu — APPROVED** [review]

**Comment by jerryjliu** [comment]
@chrispangg out of curiosity do LLMs know how to write SOSL / SOQL / do you have a sample notebook showcasing this? asking because would love to help promote :)

**Comment by chrispangg** [comment]
Hey @jerryjliu - sure thing. Let me know if the examples in this [notebook](https://colab.research.google.com/drive/12WqCdJT1vw6tfKDJnlAEJIo4LOv0WTI-?usp=sharing#scrollTo=dQajxwApYFnF) is sufficient, happy to add more if needed :)

There is a also some typos in the readme page. Will open another PR for that shortly.

**Comment by jerryjliu** [comment]
@chrispangg awesome thanks! will share this

**Comment by jerryjliu** [comment]
@chrispangg what's your twitter

**Comment by chrispangg** [comment]
All good! it's @Crispy325 on twitter 🙂

**Comment by jerryjliu** [comment]
clutch thanks!

**Pull request merged**
