### PR TITLE
adding boto3 minio doc loader

### PR DESCRIPTION
**Pull request by webcoderz**
some people prefer to use boto3 for minio  so i figured this was a decent addition,

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
thanks! could we add as a separate loader file? will show up as a separate entry in llama-hub.

if you want to group under minio, you can create a subfolder here (e.g. see the `file` folder as an example) 

also don't forget to add to library.json

**Comment by webcoderz** [comment]
Okay cool will do

**Comment by webcoderz** [comment]
ok @jerryjliu, I added the stuff into library.json and each into their own respective subdir inside minio, i also updated the library.json minio entry's id to reflect the change into subdir (id: minio/minio, boto one is id: minio/boto) now , lmk what you think

**Comment by webcoderz** [comment]
Still working on this got to make a small change or two to the variables

**Comment by EmanuelCampos** [comment]
@webcoderz There are a few errors when running the tests, could you check it, please?

**Comment by webcoderz** [comment]
Ya will do, ping when done!

**Comment by EmanuelCampos** [comment]
@jerryjliu any final thoughts on it?

**Comment by webcoderz** [comment]
@EmanuelCampos thanks I got bogged down at work 😅

**Review by jerryjliu — APPROVED** [review]

**Comment by webcoderz** [comment]
I can do some more loaders if you like , I have some ideas for things that are needed!

**Comment by EmanuelCampos** [comment]
@wenhao-mui Definitely welcome!

**Pull request merged**
