### PR TITLE
refactor: add custom path for download_loader to enable functionality…

### PR DESCRIPTION
**Pull request by jack-hughes**
… on AWS Lambda

AWS Lambda only has ephemeral storage in the /tmp directory. This means whenever attempting to use the S3Reader in conjunction with Lambda, it fails on this line.

### CODE REVIEW

**Review by jerryjliu — COMMENTED** [review]
nit: if we're going to change this, i'd prefer to have an argument in the `__init__.py` called `custom_reader_path` - will only be used if `ImportError` is triggered

speaking of which, any reason why you can't do `from llama_hub.s3.base import S3Reader` by `pip install llama-hub` as a package?

**Comment by logan-markewich** [comment]
@jerryjliu one nice thing about download loader is it install dependencies for you. Tbh I wish importing from the package did that too

**Comment by EmanuelCampos** [comment]
I'd prefer to have a custom_reader_path in `__init__py` as well, but instead of waiting for an ImportError we would use it, there's other reasons to use a custom path

**Comment by EmanuelCampos** [comment]
@logan-markewich @jerryjliu any thoughts on it? added a custom_reader_path

**Review by logan-markewich — APPROVED** [review]

**Pull request merged**
